name: ci

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install black sqlfluff

      - name: Check formatting with Black
        run: python -m black --check .

      - name: Check SQL syntax with SQLFluff (PostgreSQL)
        run: sqlfluff lint . --dialect postgres

      - name: Run tests with pytest
        run: python -m pytest tests/sql/sales_categorisation_test.py::test_sales_categorisation_query
